// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc-L_ZmBEs5NRVRMBzaHzNtgPCStONSZc',
    appId: '1:55777976578:web:b6acc1a62787a8310de21b',
    messagingSenderId: '55777976578',
    projectId: 'fir-cloud-messaging-1e84a',
    authDomain: 'fir-cloud-messaging-1e84a.firebaseapp.com',
    storageBucket: 'fir-cloud-messaging-1e84a.firebasestorage.app',
    measurementId: 'G-F07P0PRC31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvwitWhWlnV_BEqRSxg5yKs3OMFDkm3zM',
    appId: '1:55777976578:android:297dc3054acd82350de21b',
    messagingSenderId: '55777976578',
    projectId: 'fir-cloud-messaging-1e84a',
    storageBucket: 'fir-cloud-messaging-1e84a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-htvnBMq4tS_WAEvlR2JByEori2i3hhE',
    appId: '1:55777976578:ios:6bf2c31ff4ef659c0de21b',
    messagingSenderId: '55777976578',
    projectId: 'fir-cloud-messaging-1e84a',
    storageBucket: 'fir-cloud-messaging-1e84a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-htvnBMq4tS_WAEvlR2JByEori2i3hhE',
    appId: '1:55777976578:ios:6bf2c31ff4ef659c0de21b',
    messagingSenderId: '55777976578',
    projectId: 'fir-cloud-messaging-1e84a',
    storageBucket: 'fir-cloud-messaging-1e84a.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCloudMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc-L_ZmBEs5NRVRMBzaHzNtgPCStONSZc',
    appId: '1:55777976578:web:6b3c8c5e4f607ccc0de21b',
    messagingSenderId: '55777976578',
    projectId: 'fir-cloud-messaging-1e84a',
    authDomain: 'fir-cloud-messaging-1e84a.firebaseapp.com',
    storageBucket: 'fir-cloud-messaging-1e84a.firebasestorage.app',
    measurementId: 'G-489J1CD62X',
  );
}
